# Generated by Django 5.0.3 on 2024-03-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='think',
            options={'ordering': ('slug',)},
        ),
        migrations.AddField(
            model_name='think',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
