# Generated by Django 5.0.3 on 2024-04-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinks', '0002_alter_think_options_think_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='think',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
