# Generated by Django 5.0.3 on 2024-12-07 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinks', '0003_think_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='think',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 7, 12, 3, 5, 567875, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
